export const COMPANY = {
  name: "Malerfirmaet Schou & Christensen",
  shortName: "Schou & Christensen",
  address: "Ydunsvej 9",
  city: "Slagelse",
  zip: "4200",
  fullAddress: "Ydunsvej 9, 4200 Slagelse",
  phone: "53 50 77 00",
  phoneLink: "tel:+4553507700",
  email: "jess@maler-christensen.dk",
  cvr: "39187337",
  trustpilotRating: 4.9,
  trustpilotReviews: 200,
  owner: "Jess",
  domain: "maler-christensen.dk",
}

export const COLORS = {
  primary: "#6b9834",
  primaryLight: "#85bd41",
  primaryDark: "#5a8229",
}

export const SERVICES = [
  { name: "Malerarbejde", slug: "malerarbejde", description: "Generelt malerarbejde til erhverv og private" },
  { name: "Maling af carport", slug: "maling-af-carport", description: "Professionel maling af carporte og garager" },
  { name: "Maling af lejlighed", slug: "maling-af-lejlighed", description: "Komplet maling af lejligheder" },
  { name: "Maling af sommerhus", slug: "maling-af-sommerhus", description: "Udendørs og indendørs maling af sommerhuse" },
  { name: "Maling flyttelejlighed", slug: "maling-flyttelejlighed", description: "Istandsættelse ved fraflytning" },
  { name: "Maling af hus", slug: "maling-hus", description: "Komplet husmaling ude og inde" },
  { name: "Maling af trappe", slug: "maling-trappe", description: "Professionel trappemaling" },
  { name: "Tapetsering", slug: "tapetsering", description: "Professionel opsætning af tapet" },
  { name: "Træmaling", slug: "traemaling", description: "Udendørs træmaling og vedligeholdelse" },
  { name: "PCB-forsegling", slug: "pcbforsegling", description: "Indkapsling af PCB-holdige fuger" },
  { name: "Metallisk PU-gulv", slug: "metallisk-pu-gulv", description: "Eksklusive metalliske polyuretangulve" },
  { name: "Billig maler", slug: "billig-maler", description: "Kvalitetsmaling til fair priser" },
  { name: "Sprøjtespartling", slug: "sprojtespartling", description: "Hurtig og effektiv sprøjtespartling" },
  { name: "Sprøjtemaling", slug: "sproejtmaling", description: "Professionel sprøjtemaling" },
  { name: "Flisecement", slug: "flisecement", description: "Silkecement og flisecement løsninger" },
  { name: "PU-gulve", slug: "pu-gulve", description: "Polyuretangulve til alle formål" },
]

export const CITIES = [
  // Existing (keep exact slugs)
  { name: "Slagelse", slug: "maler-slagelse", distance: 0, existing: true },
  { name: "Sorø", slug: "maler-soroe", distance: 15, existing: true },
  { name: "Ringsted", slug: "malerfirma-ringsted", distance: 28, existing: true },
  { name: "Roskilde", slug: "maler-roskilde", distance: 45, existing: true },
  { name: "Næstved", slug: "maler-naestved", distance: 35, existing: true },
  { name: "Kalundborg", slug: "maler-kalundborg", distance: 40, existing: true },
  { name: "Køge", slug: "maler-koege", distance: 50, existing: true },
  // New cities
  { name: "Skælskør", slug: "maler-skaelskoer", distance: 18, existing: false },
  { name: "Korsør", slug: "maler-korsoer", distance: 12, existing: false },
  { name: "Holbæk", slug: "maler-holbaek", distance: 50, existing: false },
  { name: "Vordingborg", slug: "maler-vordingborg", distance: 55, existing: false },
  { name: "Borup", slug: "maler-borup", distance: 45, existing: false },
  { name: "Solrød", slug: "maler-solroed", distance: 55, existing: false },
  { name: "Greve", slug: "maler-greve", distance: 60, existing: false },
  { name: "København", slug: "maler-koebenhavn", distance: 80, existing: false },
  { name: "Hillerød", slug: "maler-hilleroed", distance: 90, existing: false },
  { name: "Helsingør", slug: "maler-helsingoer", distance: 100, existing: false },
  { name: "Rødovre", slug: "maler-roedovre", distance: 70, existing: false },
  { name: "Frederiksberg", slug: "maler-frederiksberg", distance: 75, existing: false },
  { name: "Charlottenlund", slug: "maler-charlottenlund", distance: 85, existing: false },
  { name: "Dragør", slug: "maler-dragoer", distance: 90, existing: false },
  { name: "Glostrup", slug: "maler-glostrup", distance: 65, existing: false },
  { name: "Ballerup", slug: "maler-ballerup", distance: 70, existing: false },
  { name: "Herlev", slug: "maler-herlev", distance: 72, existing: false },
  { name: "Kastrup", slug: "maler-kastrup", distance: 85, existing: false },
  { name: "Haslev", slug: "maler-haslev", distance: 40, existing: false },
  { name: "Lejre", slug: "maler-lejre", distance: 35, existing: false },
  { name: "Valby", slug: "maler-valby", distance: 75, existing: false },
  { name: "Gentofte", slug: "maler-gentofte", distance: 80, existing: false },
  { name: "Hvidovre", slug: "maler-hvidovre", distance: 70, existing: false },
  { name: "Lyngby", slug: "maler-lyngby", distance: 85, existing: false },
  { name: "Klampenborg", slug: "maler-klampenborg", distance: 90, existing: false },
  { name: "Nordsjælland", slug: "maler-nordsjaelland", distance: 95, existing: false },
  { name: "Lynge", slug: "maler-lynge", distance: 75, existing: false },
  { name: "Østerbro", slug: "maler-oesterbro", distance: 78, existing: false },
  { name: "Hornbæk", slug: "maler-hornbaek", distance: 110, existing: false },
  { name: "Søborg", slug: "maler-soeborg", distance: 75, existing: false },
]
